import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, ManyToOne, OneToMany, Index } from 'typeorm';
import { AlertType, AlertSeverity, AlertStatus } from '@common/enums';
import { Patient } from '../../patients/entities/patient.entity';
import { Equipment } from '../../equipment/entities/equipment.entity';
import { Location } from '../../locations/entities/location.entity';
import { User } from '../../users/entities/user.entity';
import { Notification } from '../../notifications/entities/notification.entity';

@Entity('alerts')
@Index(['status'])
@Index(['severity'])
@Index(['triggeredAt'])
export class Alert {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column({ type: 'enum', enum: AlertType })
  alertType: AlertType;

  @Column({ type: 'enum', enum: AlertSeverity, default: AlertSeverity.MEDIUM })
  severity: AlertSeverity;

  @Column({ nullable: true })
  title: string;

  @Column({ type: 'text', nullable: true })
  description: string;

  @Column({ nullable: true })
  patientId: string;

  @Column({ nullable: true })
  equipmentId: string;

  @Column({ nullable: true })
  locationId: string;

  @CreateDateColumn()
  triggeredAt: Date;

  @Column({ nullable: true })
  acknowledgedAt: Date;

  @Column({ nullable: true })
  acknowledgedById: string;

  @Column({ nullable: true })
  resolvedAt: Date;

  @Column({ nullable: true })
  resolvedById: string;

  @Column({ type: 'text', nullable: true })
  resolutionNotes: string;

  @Column({ type: 'enum', enum: AlertStatus, default: AlertStatus.OPEN })
  status: AlertStatus;

  @Column({ default: false })
  autoGenerated: boolean;

  @CreateDateColumn()
  createdAt: Date;

  // Relations
  @ManyToOne(() => Patient, { nullable: true })
  patient: Patient;

  @ManyToOne(() => Equipment, { nullable: true })
  equipment: Equipment;

  @ManyToOne(() => Location, { nullable: true })
  location: Location;

  @ManyToOne(() => User, { nullable: true })
  acknowledgedBy: User;

  @ManyToOne(() => User, { nullable: true })
  resolvedBy: User;

  @OneToMany(() => Notification, (notification) => notification.alert)
  notifications: Notification[];
}
