export enum AlertType {
  PATIENT_UNAUTHORIZED_ZONE = 'PATIENT_UNAUTHORIZED_ZONE',
  MISSING_EQUIPMENT = 'MISSING_EQUIPMENT',
  PATIENT_CRITICAL = 'PATIENT_CRITICAL',
  EQUIPMENT_MAINTENANCE_DUE = 'EQUIPMENT_MAINTENANCE_DUE',
  RESOURCE_SHORTAGE = 'RESOURCE_SHORTAGE',
  ABNORMAL_PATTERN = 'ABNORMAL_PATTERN',
}
