export enum LocationType {
  ROOM = 'ROOM',
  CORRIDOR = 'CORRIDOR',
  OPERATING_ROOM = 'OPERATING_ROOM',
  EMERGENCY = 'EMERGENCY',
  LAB = 'LAB',
  WAITING = 'WAITING',
  PHARMACY = 'PHARMACY',
  STORAGE = 'STORAGE',
  OFFICE = 'OFFICE',
}
